export { isRecord } from './record'
export { createMemoryStorage, webStorage } from './storage'
export type { KeyValueStorage } from './storage'
export { normalizePhone } from './phone'
export type { PhoneResult } from './phone'
export { MESSAGE_MAX_LENGTH, validateMessageText } from './text'
export type { TextResult } from './text'
